### ISSUE TITLE
Firebase database fields optimization

### ISSUE THREAD

**Issue by krikof** [shortcut/appshowcase-android#2]
### Info:
The endpoint for the app collection is in dire need of some newer fields. 

The new fields should be:

- An overall rating, based on the highest rating from both iOS and Android.
- An overall max install, based on the total install from both iOS and Android.

- Date fields such as releasedAndroid and releasedIos have different date formatting. Needs unified date formatting.
- Score fields such as scoreTextAndroid and scoreTextIos have different data types. One is string, the other is a float.
- Would prefer an already formatted scoreText for both platforms: eg "4.79".
- It would be nice if the Android histogram and the iOS histogram for app star ratings were reversed. Starting at 5 and counting down.
- There would be nice to have a new field called "shortestTitle" for the app title, based on the titleAndroid and titleIos field. This ensures we always get the shortest name. 

- Introduce a general category based on the genre of the app. Right now this is hard mapped in the app, based on the Android genre. 

`"navigation" -> GeneralCategory.NAVIGATION
        "health & fitness", "medical", "sports" -> GeneralCategory.HEALTH_AND_FITNESS
        "lifestyle", "other", "social networking" -> GeneralCategory.OTHER
        "travel" -> GeneralCategory.TRAVEL
        "food & drink" -> GeneralCategory.FOOD_AND_DRINK
        "shopping" -> GeneralCategory.SHOPPING
        "music", "entertainment", "magazines & newspapers", "news" -> GeneralCategory.ENTERTAINMENT
        "education" -> GeneralCategory.EDUCATION
        "reference", "utilities", "business", "finance", "productivity" -> GeneralCategory.BUSINESS
        else -> GeneralCategory.OTHER`

**Comment by bora-shortcut** [comment]
I split this into multiple cards, hence this is a duplicate.
